version: '3.8'

services:
  backend:
    build:
      context: ./backend-cars
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend-cars:/usr/src/app
    environment:
      - NODE_ENV=development
    restart: on-failure

  frontend:
    build:
      context: ./frontend-cars
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
