name: Continuous Integration and Docker Push

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend-cars/**'
      - 'backend-cars/**'


jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Lint Dockerfiles
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend-cars/Dockerfile

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend-cars/Dockerfile

  test-backend:
    needs: hadolint
    runs-on: ubuntu-latest
    name: Test Backend
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend-cars

      - name: Run backend tests
        run: npm test
        working-directory: ./backend-cars

  test-frontend:
    needs: hadolint
    runs-on: ubuntu-latest
    name: Test Frontend
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend-cars

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend-cars

  vulnerability-scan:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    name: Security Scanning
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push:
    needs: vulnerability-scan
    runs-on: ubuntu-latest
    name: Build and Push Docker images
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-cars:${{ github.run_number }} ./backend-cars
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-cars:${{ github.run_number }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-cars:${{ github.run_number }} ./frontend-cars
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-cars:${{ github.run_number }}

